### ISSUE TITLE
How can I save your phase data?

### ISSUE THREAD

**Issue by NeuraxHippo** [rookiepeng/antenna-array-analysis#7]
Your work is outstanding! I tried to save the patch and phase configuration in Windows 10, but the .csv file is not displayed(Not saved successfully) in the specified directory. I think you might know how to solve this problem.

>>arrayanalysis_Windows_x86_64
Thank you

**Comment by rookiepeng** [comment]
The export menus are place holders now. I haven't had time to implement it yet.
